import { createClient } from "@libsql/client";
import { drizzle } from "drizzle-orm/libsql";
import { recipes } from "./packages/web/src/api/database/schema";

const client = createClient({
  url: process.env.DATABASE_URL!,
  authToken: process.env.DATABASE_AUTH_TOKEN,
});
const db = drizzle(client);

const data = [
  // ── PEQUENO-ALMOÇO ──────────────────────────────────────────────
  {
    title: "Panquecas de Aveia com Banana",
    description: "Panquecas fofas e nutritivas, perfeitas para começar o dia com energia.",
    calories: 320, protein: 12, carbs: 48, fat: 8,
    prepTime: 5, cookTime: 10, servings: 2,
    category: "pequeno-almoco",
    tags: JSON.stringify(["sem-gluten", "vegetariano", "sem-acucar"]),
    ingredients: JSON.stringify(["1 banana madura", "2 ovos", "50g aveia certificada sem glúten", "1 colher chá canela", "1 colher sopa mel"]),
    steps: JSON.stringify(["Esmagar a banana com um garfo.", "Misturar com os ovos e a aveia.", "Adicionar canela.", "Fritar em frigideira antiaderente 2-3 min por lado.", "Servir com mel."]),
    imageUrl: null,
  },
  {
    title: "Iogurte Grego com Frutos Vermelhos",
    description: "Bowl proteico com frutos vermelhos frescos e granola crocante.",
    calories: 280, protein: 18, carbs: 32, fat: 6,
    prepTime: 5, cookTime: 0, servings: 1,
    category: "pequeno-almoco",
    tags: JSON.stringify(["sem-gluten", "vegetariano", "alta-proteina"]),
    ingredients: JSON.stringify(["200g iogurte grego natural", "100g morangos", "50g mirtilos", "30g granola", "1 colher sopa mel"]),
    steps: JSON.stringify(["Colocar o iogurte numa taça.", "Adicionar os frutos vermelhos.", "Polvilhar com granola.", "Regar com mel."]),
    imageUrl: null,
  },
  {
    title: "Ovos Mexidos com Espinafres",
    description: "Proteínas e ferro num prato rápido e saciante.",
    calories: 260, protein: 20, carbs: 4, fat: 18,
    prepTime: 3, cookTime: 7, servings: 1,
    category: "pequeno-almoco",
    tags: JSON.stringify(["sem-gluten", "sem-lactose", "vegetariano", "alta-proteina"]),
    ingredients: JSON.stringify(["3 ovos", "50g espinafres frescos", "1 colher sopa azeite", "sal e pimenta q.b.", "1 dente de alho"]),
    steps: JSON.stringify(["Aquecer o azeite com alho laminado.", "Adicionar espinafres e saltear 2 min.", "Bater os ovos e adicionar à frigideira.", "Mexer em lume médio-baixo.", "Temperar e servir."]),
    imageUrl: null,
  },
  {
    title: "Smoothie Bowl de Manga e Coco",
    description: "Bowl tropical rico em vitaminas e sabor.",
    calories: 340, protein: 8, carbs: 58, fat: 10,
    prepTime: 10, cookTime: 0, servings: 1,
    category: "pequeno-almoco",
    tags: JSON.stringify(["sem-gluten", "sem-lactose", "vegan", "vegetariano"]),
    ingredients: JSON.stringify(["1 manga congelada", "1 banana", "100ml leite coco", "30g granola", "10g coco ralado", "frutos vermelhos para decorar"]),
    steps: JSON.stringify(["Triturar manga, banana e leite de coco.", "Verter numa taça.", "Decorar com granola, coco e frutos vermelhos."]),
    imageUrl: null,
  },
  {
    title: "Tostas de Abacate com Ovo",
    description: "O clássico favorito: cremoso, nutritivo e delicioso.",
    calories: 380, protein: 16, carbs: 28, fat: 22,
    prepTime: 5, cookTime: 5, servings: 1,
    category: "pequeno-almoco",
    tags: JSON.stringify(["vegetariano", "alta-proteina"]),
    ingredients: JSON.stringify(["2 fatias pão integral", "1 abacate", "2 ovos", "limão q.b.", "sal e pimenta q.b.", "flocos de malagueta"]),
    steps: JSON.stringify(["Tostar o pão.", "Esmagar o abacate com sumo de limão, sal e pimenta.", "Estalar os ovos.", "Barrar o pão com abacate e colocar ovo por cima.", "Polvilhar com flocos de malagueta."]),
    imageUrl: null,
  },
  {
    title: "Overnight Oats de Morango",
    description: "Prepara à noite e tem o pequeno-almoço pronto de manhã.",
    calories: 350, protein: 14, carbs: 52, fat: 8,
    prepTime: 5, cookTime: 0, servings: 1,
    category: "pequeno-almoco",
    tags: JSON.stringify(["sem-gluten", "vegetariano"]),
    ingredients: JSON.stringify(["50g aveia certificada sem glúten", "150ml leite", "100g iogurte grego", "100g morangos", "1 colher sopa chia", "mel q.b."]),
    steps: JSON.stringify(["Misturar aveia, leite, iogurte e chia num frasco.", "Refrigerar de um dia para o outro.", "De manhã, cortar morangos por cima e regar com mel."]),
    imageUrl: null,
  },
  {
    title: "Papas de Aveia com Maçã e Canela",
    description: "Reconfortante e rico em fibra para uma manhã produtiva.",
    calories: 300, protein: 9, carbs: 54, fat: 5,
    prepTime: 2, cookTime: 8, servings: 1,
    category: "pequeno-almoco",
    tags: JSON.stringify(["sem-gluten", "vegan", "vegetariano", "sem-acucar"]),
    ingredients: JSON.stringify(["60g aveia certificada sem glúten", "300ml leite vegetal", "1 maçã", "1 colher chá canela", "1 colher sopa manteiga amendoim"]),
    steps: JSON.stringify(["Cozinhar aveia no leite vegetal mexendo sempre.", "Ralar meia maçã para dentro.", "Cortar outra metade em lâminas.", "Servir com canela e manteiga de amendoim."]),
    imageUrl: null,
  },
  {
    title: "Omelete de Cogumelos e Queijo",
    description: "Omelete recheada e saciante com cogumelos salteados.",
    calories: 310, protein: 24, carbs: 5, fat: 22,
    prepTime: 5, cookTime: 8, servings: 1,
    category: "pequeno-almoco",
    tags: JSON.stringify(["sem-gluten", "vegetariano", "alta-proteina"]),
    ingredients: JSON.stringify(["3 ovos", "100g cogumelos", "30g queijo ralado", "1 colher sopa manteiga", "cebolinho q.b.", "sal e pimenta q.b."]),
    steps: JSON.stringify(["Saltear cogumelos na manteiga.", "Bater ovos com sal e pimenta.", "Verter para frigideira em lume médio.", "Adicionar cogumelos e queijo.", "Dobrar ao meio e servir com cebolinho."]),
    imageUrl: null,
  },

  // ── ALMOÇO / JANTAR PRINCIPAL ────────────────────────────────────
  {
    title: "Frango Grelhado com Batata-doce",
    description: "Clássico fitness: proteína magra e hidratos complexos.",
    calories: 480, protein: 42, carbs: 45, fat: 10,
    prepTime: 10, cookTime: 25, servings: 2,
    category: "principal",
    tags: JSON.stringify(["sem-gluten", "sem-lactose", "alta-proteina"]),
    ingredients: JSON.stringify(["400g peito de frango", "2 batatas-doce médias", "2 colheres sopa azeite", "alho em pó q.b.", "paprika q.b.", "sal e pimenta q.b.", "limão"]),
    steps: JSON.stringify(["Cortar batata-doce em cubos e assar a 200ºC 20min.", "Temperar frango com alho, paprika, sal e pimenta.", "Grelhar 6-7 min por lado.", "Servir com batata-doce e rodelas de limão."]),
    imageUrl: null,
  },
  {
    title: "Salmão no Forno com Brócolos",
    description: "Rico em ómega-3 e antioxidantes. Pronto em 20 minutos.",
    calories: 420, protein: 38, carbs: 12, fat: 24,
    prepTime: 5, cookTime: 20, servings: 2,
    category: "principal",
    tags: JSON.stringify(["sem-gluten", "sem-lactose", "alta-proteina"]),
    ingredients: JSON.stringify(["2 filetes salmão (300g)", "300g brócolos", "2 colheres sopa azeite", "2 dentes alho", "limão", "sal e pimenta q.b.", "endro seco"]),
    steps: JSON.stringify(["Pré-aquecer forno a 200ºC.", "Dispor salmão e brócolos em tabuleiro.", "Regar com azeite, alho, limão e endro.", "Assar 18-20 minutos.", "Servir imediatamente."]),
    imageUrl: null,
  },
  {
    title: "Bowl de Quinoa com Grão e Legumes",
    description: "Proteína vegetal completa num bowl colorido e saciante.",
    calories: 440, protein: 18, carbs: 62, fat: 12,
    prepTime: 10, cookTime: 20, servings: 2,
    category: "principal",
    tags: JSON.stringify(["sem-gluten", "sem-lactose", "vegan", "vegetariano"]),
    ingredients: JSON.stringify(["150g quinoa", "200g grão cozido", "1 pepino", "1 tomate", "50g espinafres", "2 colheres sopa tahini", "limão", "sal q.b."]),
    steps: JSON.stringify(["Cozinhar quinoa em água a ferver 12-15min.", "Cortar legumes em cubos.", "Misturar tahini com limão e sal.", "Montar bowl com quinoa, grão, legumes e molho."]),
    imageUrl: null,
  },
  {
    title: "Tacos de Frango com Guacamole",
    description: "Leves e cheios de sabor. Perfeitos para um jantar rápido.",
    calories: 520, protein: 35, carbs: 42, fat: 20,
    prepTime: 15, cookTime: 15, servings: 2,
    category: "principal",
    tags: JSON.stringify(["sem-lactose", "alta-proteina"]),
    ingredients: JSON.stringify(["300g frango desfiado", "4 tortilhas de milho", "2 abacates", "1 lima", "1 tomate", "coentros q.b.", "1 cebola roxa", "pimenta q.b."]),
    steps: JSON.stringify(["Esmagar abacates com lima, coentros e sal.", "Temperar frango e grelhar 5-6 min.", "Aquecer tortilhas.", "Montar tacos com frango, guacamole, tomate e cebola."]),
    imageUrl: null,
  },
  {
    title: "Curgete Recheada com Carne Picada",
    description: "Versão low-carb deliciosa para qualquer dia da semana.",
    calories: 390, protein: 32, carbs: 14, fat: 22,
    prepTime: 10, cookTime: 30, servings: 2,
    category: "principal",
    tags: JSON.stringify(["sem-gluten", "sem-lactose", "alta-proteina"]),
    ingredients: JSON.stringify(["2 curgetes grandes", "300g carne picada", "1 tomate", "1 cebola", "2 dentes alho", "paprika q.b.", "sal e pimenta q.b.", "azeite"]),
    steps: JSON.stringify(["Cortar curgetes ao meio e esvaziar.", "Refogar cebola, alho e carne.", "Adicionar tomate e paprika, cozinhar 5 min.", "Rechear curgetes e assar a 180ºC 25 min."]),
    imageUrl: null,
  },
  {
    title: "Caril de Grão com Espinafres",
    description: "Reconfortante, aromático e 100% vegan.",
    calories: 380, protein: 16, carbs: 52, fat: 12,
    prepTime: 10, cookTime: 25, servings: 3,
    category: "principal",
    tags: JSON.stringify(["sem-gluten", "sem-lactose", "vegan", "vegetariano"]),
    ingredients: JSON.stringify(["400g grão cozido", "200g espinafres", "400ml leite de coco", "1 cebola", "2 dentes alho", "1 colher sopa caril", "1 colher chá cominhos", "tomate triturado", "azeite"]),
    steps: JSON.stringify(["Refogar cebola e alho.", "Adicionar especiarias e fritar 1 min.", "Juntar grão, tomate e leite de coco.", "Cozinhar 15 min.", "Adicionar espinafres e cozinhar mais 5 min."]),
    imageUrl: null,
  },
  {
    title: "Atum com Arroz Integral e Brócolos",
    description: "Refeição rápida, completa e económica.",
    calories: 430, protein: 36, carbs: 48, fat: 8,
    prepTime: 5, cookTime: 20, servings: 1,
    category: "principal",
    tags: JSON.stringify(["sem-gluten", "sem-lactose", "alta-proteina"]),
    ingredients: JSON.stringify(["1 lata atum em água", "80g arroz integral", "150g brócolos", "1 colher sopa azeite", "limão", "sal e pimenta q.b."]),
    steps: JSON.stringify(["Cozinhar arroz integral 20 min.", "Cozer brócolos a vapor 8 min.", "Escorrer atum.", "Misturar tudo com azeite e limão."]),
    imageUrl: null,
  },
  {
    title: "Frango ao Limão com Couscous",
    description: "Marinada cítrica e couscous fofinho. Pronto em 25 min.",
    calories: 460, protein: 38, carbs: 46, fat: 11,
    prepTime: 10, cookTime: 15, servings: 2,
    category: "principal",
    tags: JSON.stringify(["sem-lactose", "alta-proteina"]),
    ingredients: JSON.stringify(["400g frango", "150g couscous", "2 limões", "4 dentes alho", "azeite", "orégãos", "sal e pimenta q.b.", "salsa"]),
    steps: JSON.stringify(["Marinar frango com limão, alho, azeite e orégãos 10 min.", "Grelhar 6-7 min por lado.", "Preparar couscous com água quente.", "Servir com salsa picada."]),
    imageUrl: null,
  },
  {
    title: "Wraps de Peru e Hummus",
    description: "Leve, proteico e fácil de preparar para o almoço.",
    calories: 410, protein: 34, carbs: 38, fat: 12,
    prepTime: 10, cookTime: 0, servings: 2,
    category: "principal",
    tags: JSON.stringify(["alta-proteina"]),
    ingredients: JSON.stringify(["200g peito de peru cozido", "4 colheres sopa hummus", "2 tortilhas integrais", "alface", "1 tomate", "1 pepino", "sal e pimenta q.b."]),
    steps: JSON.stringify(["Barrar tortilhas com hummus.", "Fatiar peru e distribuir.", "Adicionar alface, tomate e pepino.", "Enrolar firmemente e cortar ao meio."]),
    imageUrl: null,
  },
  {
    title: "Bacalhau com Grão e Couve",
    description: "Tradicional português em versão saudável e nutritiva.",
    calories: 450, protein: 40, carbs: 38, fat: 12,
    prepTime: 15, cookTime: 20, servings: 2,
    category: "principal",
    tags: JSON.stringify(["sem-gluten", "sem-lactose", "alta-proteina"]),
    ingredients: JSON.stringify(["300g bacalhau demolhado", "200g grão cozido", "200g couve portuguesa", "3 dentes alho", "azeite", "ovo cozido", "sal e pimenta q.b."]),
    steps: JSON.stringify(["Cozer bacalhau em água 10 min.", "Saltear alho em azeite.", "Adicionar couve e refogar.", "Juntar grão e bacalhau lascado.", "Servir com ovo cozido."]),
    imageUrl: null,
  },
  {
    title: "Hambúrguer de Feijão Preto",
    description: "Hambúrguer vegan suculento com muita proteína vegetal.",
    calories: 360, protein: 16, carbs: 50, fat: 10,
    prepTime: 15, cookTime: 10, servings: 2,
    category: "principal",
    tags: JSON.stringify(["sem-gluten", "sem-lactose", "vegan", "vegetariano"]),
    ingredients: JSON.stringify(["400g feijão preto cozido", "50g aveia certificada sem glúten", "1 cebola", "2 dentes alho", "1 colher chá cominhos", "1 colher chá paprika", "sal e pimenta q.b."]),
    steps: JSON.stringify(["Esmagar feijão com garfo.", "Misturar com aveia, cebola picada e especiarias.", "Formar hambúrgueres.", "Grelhar 4-5 min por lado."]),
    imageUrl: null,
  },
  {
    title: "Massa de Lentilhas com Molho de Tomate",
    description: "Alta proteína, sem glúten e deliciosamente italiana.",
    calories: 420, protein: 22, carbs: 58, fat: 8,
    prepTime: 5, cookTime: 20, servings: 2,
    category: "principal",
    tags: JSON.stringify(["sem-gluten", "sem-lactose", "vegan", "vegetariano", "alta-proteina"]),
    ingredients: JSON.stringify(["180g massa de lentilhas", "400g tomate triturado", "1 cebola", "3 dentes alho", "manjericão", "azeite", "sal e pimenta q.b."]),
    steps: JSON.stringify(["Cozinhar massa conforme embalagem.", "Refogar cebola e alho.", "Adicionar tomate e cozinhar 15 min.", "Misturar com manjericão.", "Servir sobre a massa."]),
    imageUrl: null,
  },
  {
    title: "Frango Tikka Masala Light",
    description: "Versão levinha do clássico indiano. Aromático e irresistível.",
    calories: 390, protein: 38, carbs: 18, fat: 18,
    prepTime: 15, cookTime: 25, servings: 2,
    category: "principal",
    tags: JSON.stringify(["sem-gluten", "alta-proteina"]),
    ingredients: JSON.stringify(["400g frango", "200ml iogurte natural", "400ml tomate triturado", "1 cebola", "3 dentes alho", "1 colher sopa garam masala", "gengibre", "coentros"]),
    steps: JSON.stringify(["Marinar frango em iogurte e especiarias 30 min.", "Grelhar frango até dourar.", "Refogar cebola, alho e gengibre.", "Adicionar tomate e cozinhar 10 min.", "Juntar frango e cozinhar mais 10 min."]),
    imageUrl: null,
  },
  {
    title: "Omelete de Claras com Legumes",
    description: "Ultra-proteica e com poucas calorias. Ideal pós-treino.",
    calories: 200, protein: 28, carbs: 6, fat: 7,
    prepTime: 5, cookTime: 8, servings: 1,
    category: "principal",
    tags: JSON.stringify(["sem-gluten", "sem-lactose", "vegetariano", "alta-proteina", "sem-acucar"]),
    ingredients: JSON.stringify(["4 claras de ovo", "1 ovo inteiro", "50g pimento vermelho", "50g cebola", "50g espinafres", "azeite", "sal q.b."]),
    steps: JSON.stringify(["Bater claras com ovo.", "Saltear pimento e cebola.", "Adicionar espinafres.", "Verter ovos e cozinhar em lume médio.", "Dobrar e servir."]),
    imageUrl: null,
  },
  {
    title: "Risotto de Cogumelos e Ervilhas",
    description: "Cremoso e reconfortante. Versão vegetariana perfeita.",
    calories: 400, protein: 14, carbs: 62, fat: 10,
    prepTime: 10, cookTime: 30, servings: 2,
    category: "principal",
    tags: JSON.stringify(["vegetariano", "sem-gluten"]),
    ingredients: JSON.stringify(["150g arroz arbóreo", "200g cogumelos", "100g ervilhas", "1 cebola", "2 dentes alho", "500ml caldo legumes", "50g parmesão", "vinho branco", "manteiga"]),
    steps: JSON.stringify(["Refogar cebola e alho em manteiga.", "Adicionar arroz e tostar.", "Juntar vinho e deixar absorver.", "Adicionar caldo aos poucos mexendo sempre.", "Misturar cogumelos, ervilhas e parmesão."]),
    imageUrl: null,
  },
  {
    title: "Stir-Fry de Tofu com Legumes",
    description: "Rápido, colorido e repleto de nutrientes vegetais.",
    calories: 320, protein: 18, carbs: 28, fat: 14,
    prepTime: 10, cookTime: 12, servings: 2,
    category: "principal",
    tags: JSON.stringify(["sem-gluten", "sem-lactose", "vegan", "vegetariano"]),
    ingredients: JSON.stringify(["300g tofu firme", "1 cenoura", "1 pimento", "100g brócolos", "100g cogumelos", "3 colheres sopa molho de soja sem glúten (tamari)", "1 colher sopa óleo de sésamo", "alho", "gengibre"]),
    steps: JSON.stringify(["Cortar tofu em cubos e secar bem.", "Fritar tofu até dourar.", "Saltear legumes em lume alto.", "Adicionar molho de soja, alho e gengibre.", "Juntar tofu e óleo de sésamo."]),
    imageUrl: null,
  },
  {
    title: "Peixe Espada com Salsa Verde",
    description: "Peixe português com molho de ervas frescas.",
    calories: 360, protein: 34, carbs: 4, fat: 22,
    prepTime: 10, cookTime: 10, servings: 2,
    category: "principal",
    tags: JSON.stringify(["sem-gluten", "sem-lactose", "alta-proteina"]),
    ingredients: JSON.stringify(["2 filetes peixe espada", "salsa", "coentros", "3 dentes alho", "azeite", "limão", "sal e pimenta q.b."]),
    steps: JSON.stringify(["Triturar ervas com alho, azeite e limão.", "Temperar peixe.", "Grelhar 4-5 min por lado.", "Servir com salsa verde."]),
    imageUrl: null,
  },
  {
    title: "Sopa de Lentilhas Vermelhas",
    description: "Reconfortante, cremosa e cheia de proteína vegetal.",
    calories: 280, protein: 16, carbs: 42, fat: 5,
    prepTime: 5, cookTime: 25, servings: 3,
    category: "principal",
    tags: JSON.stringify(["sem-gluten", "sem-lactose", "vegan", "vegetariano"]),
    ingredients: JSON.stringify(["200g lentilhas vermelhas", "1 cenoura", "1 cebola", "2 dentes alho", "1 colher chá cominhos", "1 colher chá cúrcuma", "caldo legumes", "azeite"]),
    steps: JSON.stringify(["Refogar cebola, alho e especiarias.", "Adicionar cenoura em cubos.", "Juntar lentilhas e caldo.", "Cozinhar 20 min.", "Triturar parcialmente."]),
    imageUrl: null,
  },
  {
    title: "Frango com Legumes no Wok",
    description: "Refeição completa pronta em 15 minutos.",
    calories: 380, protein: 36, carbs: 22, fat: 14,
    prepTime: 10, cookTime: 12, servings: 2,
    category: "principal",
    tags: JSON.stringify(["sem-gluten", "sem-lactose", "alta-proteina"]),
    ingredients: JSON.stringify(["350g frango em tiras", "1 pimento", "1 cenoura", "100g brócolos", "3 colheres sopa molho de soja sem glúten (tamari)", "alho", "gengibre", "óleo de sésamo"]),
    steps: JSON.stringify(["Marinar frango em molho de soja.", "Saltear frango em wok bem quente.", "Adicionar legumes.", "Juntar molho, alho e gengibre.", "Finalizar com óleo de sésamo."]),
    imageUrl: null,
  },
  {
    title: "Salada Nicoise com Atum",
    description: "A clássica salada francesa: nutritiva e elegante.",
    calories: 380, protein: 30, carbs: 24, fat: 18,
    prepTime: 15, cookTime: 10, servings: 2,
    category: "principal",
    tags: JSON.stringify(["sem-gluten", "sem-lactose", "alta-proteina"]),
    ingredients: JSON.stringify(["2 latas atum", "4 ovos", "200g feijão verde", "2 tomates", "azeitonas pretas", "alface", "vinagrete de mostarda"]),
    steps: JSON.stringify(["Cozer ovos 8 min e feijão verde 5 min.", "Preparar vinagrete.", "Montar salada com todos os ingredientes.", "Temperar com vinagrete."]),
    imageUrl: null,
  },
  {
    title: "Costeletas de Porco com Maçã",
    description: "Combinação clássica: suculento e com toque adocicado.",
    calories: 430, protein: 34, carbs: 18, fat: 24,
    prepTime: 10, cookTime: 20, servings: 2,
    category: "principal",
    tags: JSON.stringify(["sem-gluten", "sem-lactose"]),
    ingredients: JSON.stringify(["4 costeletas de porco", "2 maçãs", "1 cebola", "alecrim", "azeite", "mel", "sal e pimenta q.b."]),
    steps: JSON.stringify(["Temperar costeletas com sal, pimenta e alecrim.", "Grelhar 5 min por lado.", "Saltear maçã e cebola com mel.", "Servir costeletas com compota de maçã."]),
    imageUrl: null,
  },
  {
    title: "Camarão Grelhado com Alho e Limão",
    description: "Simples, elegante e cheio de sabor do mar.",
    calories: 280, protein: 32, carbs: 4, fat: 14,
    prepTime: 10, cookTime: 8, servings: 2,
    category: "principal",
    tags: JSON.stringify(["sem-gluten", "sem-lactose", "alta-proteina"]),
    ingredients: JSON.stringify(["400g camarão", "4 dentes alho", "2 limões", "coentros", "azeite", "sal e pimenta q.b.", "malagueta"]),
    steps: JSON.stringify(["Marinar camarão com alho, limão e azeite.", "Grelhar 2-3 min por lado.", "Finalizar com coentros e sumo de limão."]),
    imageUrl: null,
  },
  {
    title: "Feijão Preto com Arroz Integral",
    description: "Proteína vegetal completa. Base da alimentação saudável.",
    calories: 420, protein: 18, carbs: 68, fat: 6,
    prepTime: 5, cookTime: 20, servings: 2,
    category: "principal",
    tags: JSON.stringify(["sem-gluten", "sem-lactose", "vegan", "vegetariano"]),
    ingredients: JSON.stringify(["200g feijão preto cozido", "80g arroz integral", "1 cebola", "3 dentes alho", "louro", "cominhos", "azeite", "sal q.b."]),
    steps: JSON.stringify(["Cozinhar arroz integral.", "Refogar cebola e alho.", "Adicionar feijão com cominhos e louro.", "Cozinhar 10 min.", "Servir sobre arroz."]),
    imageUrl: null,
  },
  {
    title: "Lombos de Pescada no Forno",
    description: "Peixe branco magro e saboroso com legumes assados.",
    calories: 320, protein: 36, carbs: 12, fat: 12,
    prepTime: 8, cookTime: 22, servings: 2,
    category: "principal",
    tags: JSON.stringify(["sem-gluten", "sem-lactose", "alta-proteina"]),
    ingredients: JSON.stringify(["2 lombos de pescada", "1 cebola", "2 tomates", "1 pimento", "azeite", "alho", "sal e pimenta q.b.", "coentros"]),
    steps: JSON.stringify(["Cortar legumes em rodelas.", "Dispor em tabuleiro com azeite e alho.", "Colocar peixe por cima.", "Temperar e assar a 180ºC 20 min."]),
    imageUrl: null,
  },

  // ── SNACKS ───────────────────────────────────────────────────────
  {
    title: "Hummus Caseiro com Palitos de Cenoura",
    description: "Snack proteico e cremoso para qualquer hora.",
    calories: 180, protein: 8, carbs: 22, fat: 7,
    prepTime: 10, cookTime: 0, servings: 3,
    category: "snack",
    tags: JSON.stringify(["sem-gluten", "sem-lactose", "vegan", "vegetariano"]),
    ingredients: JSON.stringify(["400g grão cozido", "3 colheres sopa tahini", "2 dentes alho", "limão", "azeite", "sal q.b.", "paprika", "cenouras"]),
    steps: JSON.stringify(["Triturar grão, tahini, alho e limão.", "Adicionar azeite enquanto tritura.", "Temperar com sal.", "Decorar com paprika e azeite.", "Servir com palitos de cenoura."]),
    imageUrl: null,
  },
  {
    title: "Bolas de Tâmaras e Coco",
    description: "Energy balls naturais sem açúcar adicionado.",
    calories: 120, protein: 3, carbs: 18, fat: 5,
    prepTime: 15, cookTime: 0, servings: 10,
    category: "snack",
    tags: JSON.stringify(["sem-gluten", "sem-lactose", "vegan", "vegetariano", "sem-acucar"]),
    ingredients: JSON.stringify(["200g tâmaras sem caroço", "100g amêndoa", "30g coco ralado", "1 colher chá baunilha", "pitada de sal"]),
    steps: JSON.stringify(["Triturar tâmaras e amêndoas.", "Misturar com baunilha e sal.", "Formar bolinhas.", "Rolar em coco ralado.", "Refrigerar 30 min."]),
    imageUrl: null,
  },
  {
    title: "Maçã com Manteiga de Amendoim",
    description: "Snack clássico equilibrado. Fibra + proteína + gordura boa.",
    calories: 200, protein: 6, carbs: 28, fat: 9,
    prepTime: 3, cookTime: 0, servings: 1,
    category: "snack",
    tags: JSON.stringify(["sem-gluten", "sem-lactose", "vegan", "vegetariano"]),
    ingredients: JSON.stringify(["1 maçã média", "2 colheres sopa manteiga amendoim natural", "canela opcional"]),
    steps: JSON.stringify(["Fatiar a maçã.", "Servir com manteiga de amendoim.", "Polvilhar com canela se desejar."]),
    imageUrl: null,
  },
  {
    title: "Guacamole com Chips de Beterraba",
    description: "Snack colorido, antioxidante e delicioso.",
    calories: 220, protein: 3, carbs: 20, fat: 14,
    prepTime: 15, cookTime: 20, servings: 2,
    category: "snack",
    tags: JSON.stringify(["sem-gluten", "sem-lactose", "vegan", "vegetariano"]),
    ingredients: JSON.stringify(["2 abacates", "2 beterrabas", "1 limão", "coentros", "1 cebola roxa", "sal q.b.", "azeite"]),
    steps: JSON.stringify(["Fatiar beterraba e assar a 180ºC 20min.", "Esmagar abacates com limão.", "Adicionar cebola e coentros picados.", "Temperar e servir com chips."]),
    imageUrl: null,
  },
  {
    title: "Ovos Cozidos com Sal Marinho",
    description: "O snack proteico mais simples e eficaz.",
    calories: 140, protein: 12, carbs: 1, fat: 9,
    prepTime: 2, cookTime: 10, servings: 2,
    category: "snack",
    tags: JSON.stringify(["sem-gluten", "sem-lactose", "vegetariano", "alta-proteina", "sem-acucar"]),
    ingredients: JSON.stringify(["2 ovos", "sal marinho q.b.", "pimenta q.b."]),
    steps: JSON.stringify(["Colocar ovos em água fria.", "Ferver 8-10 min.", "Arrefecer em água gelada.", "Descascar e temperar."]),
    imageUrl: null,
  },
  {
    title: "Mix de Frutos Secos",
    description: "Snack energético e portátil. Rico em gorduras boas.",
    calories: 180, protein: 5, carbs: 10, fat: 14,
    prepTime: 2, cookTime: 0, servings: 1,
    category: "snack",
    tags: JSON.stringify(["sem-gluten", "sem-lactose", "vegan", "vegetariano", "sem-acucar"]),
    ingredients: JSON.stringify(["15g amêndoas", "10g nozes", "10g cajus", "5g sementes abóbora", "3 tâmaras"]),
    steps: JSON.stringify(["Misturar todos os ingredientes.", "Servir imediatamente ou guardar em saquinho."]),
    imageUrl: null,
  },
  {
    title: "Bolachas de Arroz com Abacate",
    description: "Crocante e cremoso. Snack sem glúten e sem lactose.",
    calories: 160, protein: 3, carbs: 18, fat: 9,
    prepTime: 5, cookTime: 0, servings: 1,
    category: "snack",
    tags: JSON.stringify(["sem-gluten", "sem-lactose", "vegan", "vegetariano"]),
    ingredients: JSON.stringify(["3 bolachas de arroz", "1/2 abacate", "limão", "sal e pimenta q.b.", "sementes sésamo"]),
    steps: JSON.stringify(["Esmagar abacate com limão.", "Barrar bolachas.", "Polvilhar com sementes de sésamo e pimenta."]),
    imageUrl: null,
  },
  {
    title: "Palitos de Aipo com Queijo Fresco",
    description: "Fresco, crocante e proteico. Ideal para dieta.",
    calories: 100, protein: 8, carbs: 4, fat: 5,
    prepTime: 5, cookTime: 0, servings: 1,
    category: "snack",
    tags: JSON.stringify(["sem-gluten", "vegetariano", "sem-acucar"]),
    ingredients: JSON.stringify(["3 talos de aipo", "80g queijo fresco magro", "sal e ervas q.b."]),
    steps: JSON.stringify(["Cortar aipo em palitos.", "Temperar queijo fresco com ervas.", "Servir como dip."]),
    imageUrl: null,
  },
  {
    title: "Smoothie de Proteína de Baunilha",
    description: "Shake pós-treino rápido e saciante.",
    calories: 280, protein: 28, carbs: 24, fat: 6,
    prepTime: 5, cookTime: 0, servings: 1,
    category: "snack",
    tags: JSON.stringify(["sem-gluten", "alta-proteina"]),
    ingredients: JSON.stringify(["1 scoop proteína baunilha", "200ml leite", "1 banana", "1 colher sopa manteiga amendoim", "gelo q.b."]),
    steps: JSON.stringify(["Colocar tudo no liquidificador.", "Triturar até ficar cremoso.", "Servir imediatamente."]),
    imageUrl: null,
  },

  // ── SALADAS ──────────────────────────────────────────────────────
  {
    title: "Salada de Quinoa com Abacate",
    description: "Proteína completa, gorduras saudáveis e sabor fresco.",
    calories: 380, protein: 12, carbs: 42, fat: 18,
    prepTime: 10, cookTime: 15, servings: 2,
    category: "salada",
    tags: JSON.stringify(["sem-gluten", "sem-lactose", "vegan", "vegetariano"]),
    ingredients: JSON.stringify(["150g quinoa", "1 abacate", "1 pepino", "1 tomate", "50g rúcula", "limão", "azeite", "sal q.b."]),
    steps: JSON.stringify(["Cozinhar quinoa e deixar arrefecer.", "Cortar abacate, pepino e tomate.", "Misturar tudo.", "Temperar com limão e azeite."]),
    imageUrl: null,
  },
  {
    title: "Salada Caesar com Frango",
    description: "Versão saudável da salada mais famosa do mundo.",
    calories: 360, protein: 32, carbs: 14, fat: 20,
    prepTime: 15, cookTime: 10, servings: 2,
    category: "salada",
    tags: JSON.stringify(["alta-proteina"]),
    ingredients: JSON.stringify(["300g frango", "1 alface romana", "50g parmesão", "molho Caesar light", "croutons integrais", "limão"]),
    steps: JSON.stringify(["Grelhar frango e fatiar.", "Rasgar alface.", "Misturar com molho Caesar.", "Adicionar parmesão, croutons e frango."]),
    imageUrl: null,
  },
  {
    title: "Salada de Espinafres com Morangos",
    description: "Combinação surpreendente e deliciosa cheia de antioxidantes.",
    calories: 200, protein: 8, carbs: 20, fat: 10,
    prepTime: 10, cookTime: 0, servings: 2,
    category: "salada",
    tags: JSON.stringify(["sem-gluten", "vegetariano"]),
    ingredients: JSON.stringify(["100g espinafres baby", "150g morangos", "50g queijo feta", "30g nozes", "vinagre balsâmico", "azeite", "mel"]),
    steps: JSON.stringify(["Lavar espinafres e morangos.", "Cortar morangos ao meio.", "Preparar vinagrete com balsâmico, mel e azeite.", "Montar salada e adicionar feta e nozes."]),
    imageUrl: null,
  },
  {
    title: "Salada Grega",
    description: "Refrescante, simples e autêntica. Perfeita para o verão.",
    calories: 240, protein: 10, carbs: 16, fat: 16,
    prepTime: 10, cookTime: 0, servings: 2,
    category: "salada",
    tags: JSON.stringify(["sem-gluten", "vegetariano"]),
    ingredients: JSON.stringify(["2 tomates", "1 pepino", "1 pimento verde", "1 cebola roxa", "100g queijo feta", "azeitonas kalamata", "orégãos", "azeite"]),
    steps: JSON.stringify(["Cortar todos os legumes em pedaços.", "Misturar numa taça.", "Adicionar feta e azeitonas.", "Temperar com azeite e orégãos."]),
    imageUrl: null,
  },
  {
    title: "Salada de Grão com Atum",
    description: "Rica em proteína e muito saciante.",
    calories: 350, protein: 28, carbs: 32, fat: 10,
    prepTime: 10, cookTime: 0, servings: 2,
    category: "salada",
    tags: JSON.stringify(["sem-gluten", "sem-lactose", "alta-proteina"]),
    ingredients: JSON.stringify(["2 latas atum", "400g grão cozido", "1 pepino", "1 tomate", "cebola roxa", "salsa", "azeite", "limão", "sal q.b."]),
    steps: JSON.stringify(["Escorrer atum e grão.", "Cortar pepino, tomate e cebola.", "Misturar tudo.", "Temperar com azeite, limão e salsa."]),
    imageUrl: null,
  },

  // ── SOPAS ────────────────────────────────────────────────────────
  {
    title: "Sopa de Cenoura e Gengibre",
    description: "Anti-inflamatória, cremosa e reconfortante.",
    calories: 160, protein: 3, carbs: 28, fat: 4,
    prepTime: 10, cookTime: 25, servings: 3,
    category: "sopa",
    tags: JSON.stringify(["sem-gluten", "sem-lactose", "vegan", "vegetariano", "sem-acucar"]),
    ingredients: JSON.stringify(["4 cenouras", "1 cebola", "2cm gengibre fresco", "1 colher chá cúrcuma", "caldo legumes", "leite de coco", "azeite"]),
    steps: JSON.stringify(["Refogar cebola e gengibre.", "Adicionar cenoura e cúrcuma.", "Cobrir com caldo e cozinhar 20 min.", "Triturar.", "Adicionar leite de coco."]),
    imageUrl: null,
  },
  {
    title: "Caldo Verde",
    description: "O clássico português saudável e reconfortante.",
    calories: 180, protein: 8, carbs: 22, fat: 6,
    prepTime: 10, cookTime: 30, servings: 4,
    category: "sopa",
    tags: JSON.stringify(["sem-gluten", "sem-lactose"]),
    ingredients: JSON.stringify(["4 batatas", "300g couve galega", "1 chouriço", "1 cebola", "3 dentes alho", "azeite", "sal e pimenta q.b."]),
    steps: JSON.stringify(["Cozer batatas com cebola e alho.", "Triturar batatas.", "Cortar couve em juliana fina.", "Adicionar couve à sopa e cozinhar 5 min.", "Adicionar rodelas de chouriço e azeite."]),
    imageUrl: null,
  },
  {
    title: "Sopa Creme de Abóbora",
    description: "Doce, cremosa e cheia de beta-caroteno.",
    calories: 150, protein: 3, carbs: 26, fat: 4,
    prepTime: 10, cookTime: 25, servings: 3,
    category: "sopa",
    tags: JSON.stringify(["sem-gluten", "sem-lactose", "vegan", "vegetariano"]),
    ingredients: JSON.stringify(["600g abóbora", "1 cebola", "2 dentes alho", "caldo legumes", "noz moscada", "azeite", "sal q.b."]),
    steps: JSON.stringify(["Refogar cebola e alho.", "Adicionar abóbora em cubos.", "Cobrir com caldo e cozinhar 20 min.", "Triturar.", "Temperar com noz moscada."]),
    imageUrl: null,
  },
  {
    title: "Sopa de Tomate com Manjericão",
    description: "Fresca, aromática e cheia de licopeno.",
    calories: 140, protein: 4, carbs: 22, fat: 4,
    prepTime: 8, cookTime: 20, servings: 3,
    category: "sopa",
    tags: JSON.stringify(["sem-gluten", "sem-lactose", "vegan", "vegetariano"]),
    ingredients: JSON.stringify(["800g tomate maduro", "1 cebola", "3 dentes alho", "manjericão fresco", "caldo legumes", "azeite", "sal e pimenta q.b."]),
    steps: JSON.stringify(["Refogar cebola e alho.", "Adicionar tomate.", "Cozinhar 15 min.", "Triturar.", "Adicionar manjericão fresco."]),
    imageUrl: null,
  },
  {
    title: "Sopa de Feijão Verde com Batata",
    description: "Simples, caseira e muito nutritiva.",
    calories: 170, protein: 6, carbs: 30, fat: 3,
    prepTime: 10, cookTime: 25, servings: 3,
    category: "sopa",
    tags: JSON.stringify(["sem-gluten", "sem-lactose", "vegan", "vegetariano"]),
    ingredients: JSON.stringify(["200g feijão verde", "2 batatas", "1 cenoura", "1 cebola", "2 dentes alho", "caldo legumes", "azeite", "sal q.b."]),
    steps: JSON.stringify(["Refogar cebola e alho.", "Adicionar batatas e cenoura.", "Cobrir com caldo e cozinhar 15 min.", "Adicionar feijão verde e cozinhar mais 10 min.", "Temperar e servir."]),
    imageUrl: null,
  },

  // ── SOBREMESAS ───────────────────────────────────────────────────
  {
    title: "Mousse de Chocolate Negro",
    description: "Indulgente mas saudável. Com abacate como base.",
    calories: 240, protein: 5, carbs: 22, fat: 16,
    prepTime: 10, cookTime: 0, servings: 3,
    category: "sobremesa",
    tags: JSON.stringify(["sem-gluten", "sem-lactose", "vegan", "vegetariano"]),
    ingredients: JSON.stringify(["2 abacates maduros", "4 colheres sopa cacau em pó", "3 colheres sopa xarope de ácer", "1 colher chá baunilha", "pitada de sal"]),
    steps: JSON.stringify(["Triturar tudo até ficar cremoso.", "Provar e ajustar xarope de ácer.", "Refrigerar 30 min.", "Servir em taças."]),
    imageUrl: null,
  },
  {
    title: "Gelado de Banana de 1 Ingrediente",
    description: "Cremoso, doce e zero culpa. Só banana!",
    calories: 105, protein: 1, carbs: 27, fat: 0,
    prepTime: 5, cookTime: 0, servings: 1,
    category: "sobremesa",
    tags: JSON.stringify(["sem-gluten", "sem-lactose", "vegan", "vegetariano", "sem-acucar"]),
    ingredients: JSON.stringify(["2 bananas maduras congeladas"]),
    steps: JSON.stringify(["Cortar bananas em rodelas e congelar.", "Triturar na picadora até ficar cremoso.", "Servir imediatamente ou recongelar 1h."]),
    imageUrl: null,
  },
  {
    title: "Chia Pudding de Frutos Vermelhos",
    description: "Rico em ómega-3 e fibra. Prepara à noite.",
    calories: 220, protein: 8, carbs: 28, fat: 10,
    prepTime: 5, cookTime: 0, servings: 2,
    category: "sobremesa",
    tags: JSON.stringify(["sem-gluten", "sem-lactose", "vegan", "vegetariano", "sem-acucar"]),
    ingredients: JSON.stringify(["4 colheres sopa sementes chia", "300ml leite de amêndoa", "1 colher sopa xarope de ácer", "100g frutos vermelhos"]),
    steps: JSON.stringify(["Misturar chia com leite e xarope de ácer.", "Refrigerar 4h ou de um dia para o outro.", "Servir com frutos vermelhos."]),
    imageUrl: null,
  },
  {
    title: "Bolo de Cenoura sem Farinha",
    description: "Húmido, saboroso e sem glúten.",
    calories: 200, protein: 6, carbs: 24, fat: 10,
    prepTime: 15, cookTime: 30, servings: 8,
    category: "sobremesa",
    tags: JSON.stringify(["sem-gluten", "vegetariano"]),
    ingredients: JSON.stringify(["3 cenouras", "3 ovos", "100g amêndoa moída", "80g açúcar de coco", "2 colheres sopa azeite", "1 colher chá fermento", "canela"]),
    steps: JSON.stringify(["Ralar cenouras.", "Bater ovos com açúcar.", "Adicionar amêndoa, cenoura, azeite e canela.", "Juntar fermento.", "Assar a 180ºC 30 min."]),
    imageUrl: null,
  },
  {
    title: "Compota de Maçã Sem Açúcar",
    description: "Doce natural para acompanhar iogurte ou panquecas.",
    calories: 80, protein: 0, carbs: 20, fat: 0,
    prepTime: 5, cookTime: 20, servings: 6,
    category: "sobremesa",
    tags: JSON.stringify(["sem-gluten", "sem-lactose", "vegan", "vegetariano", "sem-acucar"]),
    ingredients: JSON.stringify(["6 maçãs", "1 colher chá canela", "sumo de 1 limão", "1 colher sopa xarope de ácer"]),
    steps: JSON.stringify(["Descascar e cortar maçãs.", "Cozinhar com limão e canela 15-20 min.", "Esmagar com garfo.", "Adicionar xarope de ácer se desejar."]),
    imageUrl: null,
  },

  // ── BEBIDAS / SMOOTHIES ──────────────────────────────────────────
  {
    title: "Green Smoothie Detox",
    description: "Repleto de clorofila, vitaminas e energia.",
    calories: 160, protein: 4, carbs: 30, fat: 3,
    prepTime: 5, cookTime: 0, servings: 1,
    category: "bebida",
    tags: JSON.stringify(["sem-gluten", "sem-lactose", "vegan", "vegetariano", "sem-acucar"]),
    ingredients: JSON.stringify(["1 banana", "100g espinafres", "1/2 pepino", "1 maçã verde", "sumo 1 limão", "200ml água de coco", "gengibre q.b."]),
    steps: JSON.stringify(["Colocar tudo no liquidificador.", "Triturar até ficar homogéneo.", "Servir com gelo."]),
    imageUrl: null,
  },
  {
    title: "Smoothie Tropical de Abacaxi",
    description: "Anti-inflamatório e refrescante. Sabor verão o ano todo.",
    calories: 180, protein: 3, carbs: 38, fat: 2,
    prepTime: 5, cookTime: 0, servings: 1,
    category: "bebida",
    tags: JSON.stringify(["sem-gluten", "sem-lactose", "vegan", "vegetariano", "sem-acucar"]),
    ingredients: JSON.stringify(["200g abacaxi", "1 banana", "100ml leite coco", "1cm gengibre", "1 colher chá cúrcuma", "gelo"]),
    steps: JSON.stringify(["Triturar tudo.", "Servir com gelo."]),
    imageUrl: null,
  },
  {
    title: "Leite Dourado (Golden Milk)",
    description: "Anti-inflamatório, calmante e perfeito antes de dormir.",
    calories: 120, protein: 3, carbs: 14, fat: 5,
    prepTime: 3, cookTime: 5, servings: 1,
    category: "bebida",
    tags: JSON.stringify(["sem-gluten", "vegetariano", "sem-acucar"]),
    ingredients: JSON.stringify(["300ml leite", "1 colher chá cúrcuma", "1/2 colher chá canela", "1/4 colher chá gengibre", "pitada pimenta preta", "mel q.b."]),
    steps: JSON.stringify(["Aquecer leite em lume médio.", "Adicionar todas as especiarias.", "Mexer bem.", "Adoçar com mel e servir quente."]),
    imageUrl: null,
  },

  // ── REFEIÇÕES PÓS-TREINO ─────────────────────────────────────────
  {
    title: "Bowl Pós-Treino de Arroz e Frango",
    description: "Recuperação muscular optimizada: carbos + proteína.",
    calories: 520, protein: 45, carbs: 55, fat: 10,
    prepTime: 5, cookTime: 20, servings: 1,
    category: "principal",
    tags: JSON.stringify(["sem-gluten", "sem-lactose", "alta-proteina"]),
    ingredients: JSON.stringify(["150g frango", "80g arroz branco", "50g espinafres", "1 ovo", "azeite", "sal e pimenta q.b."]),
    steps: JSON.stringify(["Cozinhar arroz.", "Grelhar frango temperado.", "Saltear espinafres.", "Montar bowl e adicionar ovo estrelado."]),
    imageUrl: null,
  },
  {
    title: "Wrap de Frango com Arroz e Feijão",
    description: "Compacto, completo e perfeito para levar na mochila.",
    calories: 480, protein: 38, carbs: 52, fat: 10,
    prepTime: 10, cookTime: 15, servings: 1,
    category: "principal",
    tags: JSON.stringify(["alta-proteina"]),
    ingredients: JSON.stringify(["150g frango grelhado", "60g arroz", "50g feijão preto", "1 tortilha integral", "salsa", "limão", "sal q.b."]),
    steps: JSON.stringify(["Cozinhar arroz e feijão.", "Grelhar frango.", "Aquecer tortilha.", "Montar e enrolar."]),
    imageUrl: null,
  },

  // ── RECEITAS ESPECIAIS ───────────────────────────────────────────
  {
    title: "Pão de Banana Sem Glúten",
    description: "Fofinho, húmido e sem farinha de trigo.",
    calories: 180, protein: 5, carbs: 28, fat: 6,
    prepTime: 10, cookTime: 40, servings: 8,
    category: "pequeno-almoco",
    tags: JSON.stringify(["sem-gluten", "vegetariano"]),
    ingredients: JSON.stringify(["3 bananas maduras", "2 ovos", "100g farinha de amêndoa", "50g aveia certificada sem glúten", "1 colher chá canela", "1 colher chá fermento", "mel"]),
    steps: JSON.stringify(["Esmagar bananas.", "Misturar com ovos e mel.", "Adicionar farinha, aveia, canela e fermento.", "Verter em forma untada.", "Assar a 175ºC 40 min."]),
    imageUrl: null,
  },
  {
    title: "Granola Caseira Sem Açúcar",
    description: "Crocante, nutritiva e sem açúcar adicionado.",
    calories: 220, protein: 6, carbs: 28, fat: 10,
    prepTime: 5, cookTime: 25, servings: 8,
    category: "pequeno-almoco",
    tags: JSON.stringify(["sem-gluten", "sem-lactose", "vegan", "vegetariano", "sem-acucar"]),
    ingredients: JSON.stringify(["200g aveia certificada sem glúten", "50g amêndoas", "50g nozes", "30g sementes girassol", "3 colheres sopa xarope de ácer", "2 colheres sopa óleo coco", "canela"]),
    steps: JSON.stringify(["Misturar aveia, frutos secos e sementes.", "Adicionar xarope de ácer e óleo de coco.", "Espalhar em tabuleiro.", "Assar a 160ºC 25 min mexendo a meio."]),
    imageUrl: null,
  },
  {
    title: "Muffins de Espinafres e Queijo",
    description: "Muffins salgados proteicos perfeitos para snack.",
    calories: 160, protein: 10, carbs: 12, fat: 8,
    prepTime: 10, cookTime: 20, servings: 6,
    category: "snack",
    tags: JSON.stringify(["vegetariano", "alta-proteina"]),
    ingredients: JSON.stringify(["100g espinafres", "3 ovos", "100g queijo ralado", "100g farinha integral", "100ml leite", "1 colher chá fermento", "sal e pimenta q.b."]),
    steps: JSON.stringify(["Saltear espinafres.", "Bater ovos com leite.", "Misturar com farinha e fermento.", "Adicionar espinafres e queijo.", "Assar a 180ºC 20 min."]),
    imageUrl: null,
  },
  {
    title: "Frittata de Legumes",
    description: "A omelete italiana assada no forno. Versátil e deliciosa.",
    calories: 280, protein: 20, carbs: 10, fat: 18,
    prepTime: 10, cookTime: 20, servings: 3,
    category: "principal",
    tags: JSON.stringify(["sem-gluten", "vegetariano", "alta-proteina"]),
    ingredients: JSON.stringify(["6 ovos", "1 curgete", "1 pimento", "1 cebola", "50g queijo feta", "ervas provençais", "azeite", "sal q.b."]),
    steps: JSON.stringify(["Saltear legumes.", "Bater ovos com sal e ervas.", "Misturar com legumes.", "Verter em frigideira e assar 180ºC 15 min.", "Acabar com feta por cima."]),
    imageUrl: null,
  },
  {
    title: "Dahl de Lentilhas",
    description: "Receita indiana reconfortante, vegan e económica.",
    calories: 350, protein: 18, carbs: 54, fat: 7,
    prepTime: 10, cookTime: 30, servings: 3,
    category: "principal",
    tags: JSON.stringify(["sem-gluten", "sem-lactose", "vegan", "vegetariano"]),
    ingredients: JSON.stringify(["250g lentilhas vermelhas", "400ml leite coco", "1 cebola", "3 dentes alho", "1 colher sopa caril", "1 colher chá cúrcuma", "cominhos", "tomate triturado"]),
    steps: JSON.stringify(["Refogar cebola, alho e especiarias.", "Adicionar lentilhas.", "Juntar leite de coco e tomate.", "Cozinhar 25 min.", "Ajustar temperos."]),
    imageUrl: null,
  },
  {
    title: "Espetadas de Legumes Grelhados",
    description: "Coloridas, saudáveis e perfeitas para o verão.",
    calories: 180, protein: 5, carbs: 24, fat: 8,
    prepTime: 15, cookTime: 15, servings: 2,
    category: "principal",
    tags: JSON.stringify(["sem-gluten", "sem-lactose", "vegan", "vegetariano", "sem-acucar"]),
    ingredients: JSON.stringify(["1 curgete", "1 pimento vermelho", "1 pimento amarelo", "1 beringela", "cogumelos", "azeite", "alho", "ervas q.b."]),
    steps: JSON.stringify(["Cortar legumes em cubos.", "Temperar com azeite, alho e ervas.", "Espetar alternando legumes.", "Grelhar 12-15 min virando."]),
    imageUrl: null,
  },
  {
    title: "Papas de Aveia Salgadas com Ovo",
    description: "A versão salgada das papas. Saciante e diferente.",
    calories: 310, protein: 18, carbs: 36, fat: 10,
    prepTime: 3, cookTime: 10, servings: 1,
    category: "pequeno-almoco",
    tags: JSON.stringify(["sem-gluten", "vegetariano", "alta-proteina"]),
    ingredients: JSON.stringify(["60g aveia certificada sem glúten", "300ml caldo vegetal", "1 ovo", "30g queijo ralado", "cebolinho", "sal e pimenta q.b."]),
    steps: JSON.stringify(["Cozinhar aveia no caldo.", "Mexer até cremosa.", "Adicionar queijo.", "Colocar ovo escalfado por cima.", "Polvilhar cebolinho."]),
    imageUrl: null,
  },
  {
    title: "Salada de Massa de Lentilhas Fria",
    description: "Leve, proteica e ideal para levar para o trabalho.",
    calories: 340, protein: 20, carbs: 46, fat: 8,
    prepTime: 10, cookTime: 10, servings: 2,
    category: "salada",
    tags: JSON.stringify(["sem-gluten", "sem-lactose", "vegan", "vegetariano", "alta-proteina"]),
    ingredients: JSON.stringify(["150g massa de lentilhas", "1 pepino", "1 tomate", "azeitonas", "salsa", "azeite", "limão", "sal q.b."]),
    steps: JSON.stringify(["Cozinhar massa e arrefecer.", "Cortar legumes.", "Misturar tudo.", "Temperar com azeite e limão."]),
    imageUrl: null,
  },
  {
    title: "Bolonhesa de Lentilhas",
    description: "Versão vegan do molho bolonhesa. Ninguém vai notar a diferença!",
    calories: 380, protein: 20, carbs: 56, fat: 6,
    prepTime: 10, cookTime: 30, servings: 3,
    category: "principal",
    tags: JSON.stringify(["sem-lactose", "vegan", "vegetariano"]),
    ingredients: JSON.stringify(["200g lentilhas verdes", "400g tomate triturado", "1 cenoura", "1 cebola", "2 dentes alho", "aipo", "vinho tinto", "orégãos", "azeite"]),
    steps: JSON.stringify(["Refogar cebola, alho, cenoura e aipo.", "Adicionar lentilhas.", "Juntar tomate e vinho.", "Cozinhar 25 min.", "Servir com massa ou espaguete de curgete."]),
    imageUrl: null,
  },
  {
    title: "Beringela no Forno com Parmesão",
    description: "Vegetariana, cremosa e muito saborosa.",
    calories: 240, protein: 12, carbs: 18, fat: 14,
    prepTime: 10, cookTime: 30, servings: 2,
    category: "principal",
    tags: JSON.stringify(["sem-gluten", "vegetariano"]),
    ingredients: JSON.stringify(["2 beringelas", "400g tomate triturado", "100g parmesão", "manjericão", "azeite", "alho", "sal e pimenta q.b."]),
    steps: JSON.stringify(["Fatiar beringela e grelhar.", "Fazer molho de tomate com alho.", "Montar camadas em tabuleiro.", "Polvilhar parmesão.", "Assar 180ºC 20 min."]),
    imageUrl: null,
  },
];

async function seed() {
  console.log(`Inserindo ${data.length} receitas...`);
  // Insert in batches of 10
  for (let i = 0; i < data.length; i += 10) {
    const batch = data.slice(i, i + 10);
    await db.insert(recipes).values(batch);
    console.log(`✅ ${Math.min(i + 10, data.length)}/${data.length}`);
  }
  console.log("🎉 Todas as receitas inseridas!");
  process.exit(0);
}

seed().catch((e) => { console.error(e); process.exit(1); });
