import { createClient } from "@libsql/client";
import { drizzle } from "drizzle-orm/libsql";
import { recipes } from "./src/api/database/schema";

const client = createClient({
  url: process.env.DATABASE_URL!,
  authToken: process.env.DATABASE_AUTH_TOKEN,
});
const db = drizzle(client);

const data = [
  {
    title: "Açaí Bowl Energético",
    description: "Bowl de açaí com frutos tropicais e granola. Explosão de energia.",
    calories: 360, protein: 8, carbs: 58, fat: 12,
    prepTime: 8, cookTime: 0, servings: 1,
    category: "pequeno-almoco",
    tags: JSON.stringify(["sem-gluten", "sem-lactose", "vegan", "vegetariano"]),
    ingredients: JSON.stringify(["100g açaí congelado", "1 banana", "100ml leite de coco", "30g granola", "morangos", "kiwi", "mel"]),
    steps: JSON.stringify(["Triturar açaí com banana e leite de coco.", "Verter em taça.", "Decorar com granola, morangos e kiwi.", "Regar com mel."]),
    imageUrl: null,
  },
  {
    title: "Taça de Cottage com Pepino",
    description: "Snack refrescante e proteico. Pronto em 2 minutos.",
    calories: 140, protein: 16, carbs: 8, fat: 4,
    prepTime: 2, cookTime: 0, servings: 1,
    category: "snack",
    tags: JSON.stringify(["sem-gluten", "vegetariano", "alta-proteina", "sem-acucar"]),
    ingredients: JSON.stringify(["150g queijo cottage", "1/2 pepino", "aneto seco", "sal e pimenta q.b.", "azeite"]),
    steps: JSON.stringify(["Fatiar pepino.", "Temperar cottage com sal, pimenta e aneto.", "Servir com rodelas de pepino."]),
    imageUrl: null,
  },
  {
    title: "Frango Assado com Ervas",
    description: "Clássico de domingo mas saudável e aromático.",
    calories: 460, protein: 44, carbs: 8, fat: 26,
    prepTime: 15, cookTime: 45, servings: 4,
    category: "principal",
    tags: JSON.stringify(["sem-gluten", "sem-lactose", "alta-proteina"]),
    ingredients: JSON.stringify(["1 frango inteiro", "alecrim", "tomilho", "4 dentes alho", "1 limão", "azeite", "sal e pimenta q.b."]),
    steps: JSON.stringify(["Temperar frango por dentro e por fora.", "Rechear com limão e alho.", "Regar com azeite.", "Assar a 190ºC 45-50 min.", "Deixar repousar 10 min antes de cortar."]),
    imageUrl: null,
  },
  {
    title: "Sopa de Ervilhas com Hortelã",
    description: "Verde, fresca e com um toque aromático especial.",
    calories: 160, protein: 8, carbs: 24, fat: 4,
    prepTime: 5, cookTime: 15, servings: 3,
    category: "sopa",
    tags: JSON.stringify(["sem-gluten", "sem-lactose", "vegan", "vegetariano"]),
    ingredients: JSON.stringify(["400g ervilhas congeladas", "1 cebola", "2 dentes alho", "caldo vegetal", "hortelã fresca", "azeite", "sal q.b."]),
    steps: JSON.stringify(["Refogar cebola e alho.", "Adicionar ervilhas e caldo.", "Cozinhar 10 min.", "Triturar com hortelã.", "Ajustar sal e servir."]),
    imageUrl: null,
  },
  {
    title: "Panquecas Proteicas de Queijo Fresco",
    description: "Leves, proteicas e deliciosas. Perfeitas pós-treino.",
    calories: 280, protein: 22, carbs: 26, fat: 9,
    prepTime: 5, cookTime: 10, servings: 2,
    category: "pequeno-almoco",
    tags: JSON.stringify(["sem-gluten", "vegetariano", "alta-proteina"]),
    ingredients: JSON.stringify(["150g queijo fresco", "2 ovos", "30g aveia", "1 banana", "1 colher chá fermento", "mel para servir"]),
    steps: JSON.stringify(["Triturar todos os ingredientes.", "Fritar colheradas em frigideira antiaderente.", "2-3 min por lado.", "Servir com mel."]),
    imageUrl: null,
  },
  {
    title: "Ceviche de Peixe Branco",
    description: "Fresco, cítrico e repleto de sabores mediterrâneos.",
    calories: 220, protein: 28, carbs: 10, fat: 7,
    prepTime: 20, cookTime: 0, servings: 2,
    category: "principal",
    tags: JSON.stringify(["sem-gluten", "sem-lactose", "alta-proteina", "sem-acucar"]),
    ingredients: JSON.stringify(["300g peixe branco fresco", "3 limas", "1 limão", "1 cebola roxa", "coentros", "1 malagueta", "sal q.b."]),
    steps: JSON.stringify(["Cortar peixe em cubos pequenos.", "Marinar com sumo de lima e limão 15 min.", "Adicionar cebola, coentros e malagueta.", "Servir fresco."]),
    imageUrl: null,
  },
  {
    title: "Arroz de Pato Light",
    description: "Versão mais leve do clássico arroz de pato.",
    calories: 480, protein: 32, carbs: 52, fat: 14,
    prepTime: 20, cookTime: 40, servings: 3,
    category: "principal",
    tags: JSON.stringify(["sem-gluten", "sem-lactose"]),
    ingredients: JSON.stringify(["2 pernas de pato", "150g arroz", "1 chouriço", "1 cebola", "2 dentes alho", "louro", "azeite", "sal q.b."]),
    steps: JSON.stringify(["Cozer pato 30 min.", "Desossár e desfiar.", "Refogar cebola, alho e chouriço.", "Adicionar arroz e caldo de pato.", "Cozinhar 18 min e misturar pato."]),
    imageUrl: null,
  },
  {
    title: "Barras de Aveia e Frutos Secos",
    description: "Snack energético caseiro para levar na mochila.",
    calories: 180, protein: 5, carbs: 24, fat: 8,
    prepTime: 10, cookTime: 20, servings: 8,
    category: "snack",
    tags: JSON.stringify(["sem-gluten", "sem-lactose", "vegan", "vegetariano"]),
    ingredients: JSON.stringify(["150g aveia", "50g tâmaras", "30g amêndoas", "30g passas", "3 colheres sopa mel", "2 colheres sopa óleo coco", "canela"]),
    steps: JSON.stringify(["Triturar tâmaras.", "Misturar com aveia, frutos secos, mel e óleo.", "Pressionar em tabuleiro forrado.", "Assar 180ºC 20 min.", "Arrefecer e cortar em barras."]),
    imageUrl: null,
  },
  {
    title: "Esparguete de Curgete com Pesto",
    description: "Alternativa low-carb à massa tradicional. Leve e deliciosa.",
    calories: 260, protein: 8, carbs: 14, fat: 20,
    prepTime: 15, cookTime: 5, servings: 2,
    category: "principal",
    tags: JSON.stringify(["sem-gluten", "vegetariano"]),
    ingredients: JSON.stringify(["3 curgetes", "3 colheres sopa pesto", "tomates cherry", "parmesão", "pinhões", "sal q.b."]),
    steps: JSON.stringify(["Espiralizar curgetes.", "Saltear 2-3 min.", "Misturar pesto.", "Adicionar tomates cherry.", "Terminar com parmesão e pinhões."]),
    imageUrl: null,
  },
  {
    title: "Pudim de Chia com Maracujá",
    description: "Exótico, cremoso e rico em ómega-3.",
    calories: 200, protein: 7, carbs: 26, fat: 9,
    prepTime: 5, cookTime: 0, servings: 2,
    category: "sobremesa",
    tags: JSON.stringify(["sem-gluten", "sem-lactose", "vegan", "vegetariano", "sem-acucar"]),
    ingredients: JSON.stringify(["4 colheres sopa chia", "300ml leite de coco", "2 maracujás", "mel q.b.", "hortelã"]),
    steps: JSON.stringify(["Misturar chia com leite de coco.", "Refrigerar 4h.", "Abrir maracujás.", "Servir chia com polpa de maracujá e hortelã."]),
    imageUrl: null,
  },
  {
    title: "Salada Tailandesa de Papaia",
    description: "Som Tam vegano com papaia verde ralada e amendoim.",
    calories: 180, protein: 5, carbs: 28, fat: 7,
    prepTime: 15, cookTime: 0, servings: 2,
    category: "salada",
    tags: JSON.stringify(["sem-gluten", "sem-lactose", "vegan", "vegetariano"]),
    ingredients: JSON.stringify(["1 papaia verde", "amendoim torrado", "tomates cherry", "1 malagueta", "molho soja", "limão", "mel", "coentros"]),
    steps: JSON.stringify(["Ralar papaia verde.", "Preparar molho com soja, limão, mel e malagueta.", "Misturar tudo.", "Finalizar com amendoim e coentros."]),
    imageUrl: null,
  },
  {
    title: "Cogumelos Portobello Recheados",
    description: "Recheio cremoso de queijo e espinafres. Elegante e fácil.",
    calories: 220, protein: 14, carbs: 10, fat: 14,
    prepTime: 10, cookTime: 20, servings: 2,
    category: "principal",
    tags: JSON.stringify(["sem-gluten", "vegetariano"]),
    ingredients: JSON.stringify(["4 cogumelos portobello", "100g espinafres", "100g ricotta", "50g parmesão", "2 dentes alho", "azeite", "sal q.b."]),
    steps: JSON.stringify(["Limpar cogumelos e remover pé.", "Saltear espinafres e alho.", "Misturar com ricotta.", "Rechear cogumelos.", "Polvilhar parmesão e assar 180ºC 20 min."]),
    imageUrl: null,
  },
  {
    title: "Crepes de Trigo Sarraceno",
    description: "Sem glúten, finos e versáteis. Doces ou salgados.",
    calories: 180, protein: 7, carbs: 28, fat: 5,
    prepTime: 5, cookTime: 15, servings: 4,
    category: "pequeno-almoco",
    tags: JSON.stringify(["sem-gluten", "vegetariano"]),
    ingredients: JSON.stringify(["100g farinha trigo sarraceno", "2 ovos", "250ml leite", "1 colher sopa azeite", "pitada sal"]),
    steps: JSON.stringify(["Misturar todos os ingredientes.", "Deixar repousar 15 min.", "Fritar colheradas em frigideira quente.", "Virar quando estiver firme."]),
    imageUrl: null,
  },
  {
    title: "Panna Cotta de Coco",
    description: "Sobremesa elegante, leve e sem lactose.",
    calories: 180, protein: 3, carbs: 20, fat: 10,
    prepTime: 10, cookTime: 5, servings: 4,
    category: "sobremesa",
    tags: JSON.stringify(["sem-gluten", "sem-lactose", "vegan", "vegetariano"]),
    ingredients: JSON.stringify(["400ml leite de coco", "2 colheres sopa açúcar", "2 colheres chá ágar-ágar", "baunilha", "frutos vermelhos para servir"]),
    steps: JSON.stringify(["Aquecer leite de coco com açúcar e baunilha.", "Dissolver ágar-ágar.", "Verter em forminhas.", "Refrigerar 3h.", "Desenformar e servir com frutos vermelhos."]),
    imageUrl: null,
  },
  {
    title: "Sopa de Miso com Tofu",
    description: "Reconfortante sopa japonesa rica em probióticos.",
    calories: 130, protein: 10, carbs: 8, fat: 6,
    prepTime: 5, cookTime: 10, servings: 2,
    category: "sopa",
    tags: JSON.stringify(["sem-gluten", "sem-lactose", "vegan", "vegetariano"]),
    ingredients: JSON.stringify(["2 colheres sopa pasta miso", "150g tofu firme", "algas wakame", "cebolinho", "600ml água"]),
    steps: JSON.stringify(["Aquecer água sem ferver.", "Dissolver miso.", "Adicionar tofu em cubos e algas.", "Servir com cebolinho."]),
    imageUrl: null,
  },
  {
    title: "Frango Teriyaki com Brócolo",
    description: "Sabores asiáticos saudáveis e irresistíveis.",
    calories: 400, protein: 38, carbs: 28, fat: 12,
    prepTime: 10, cookTime: 20, servings: 2,
    category: "principal",
    tags: JSON.stringify(["sem-lactose", "alta-proteina"]),
    ingredients: JSON.stringify(["350g frango", "300g brócolos", "3 colheres sopa molho soja", "1 colher sopa mel", "1 colher chá gengibre", "alho", "óleo sésamo"]),
    steps: JSON.stringify(["Misturar molho teriyaki (soja+mel+gengibre+alho).", "Marinar frango 10 min.", "Grelhar frango 6-7 min por lado.", "Saltear brócolos.", "Servir com molho por cima."]),
    imageUrl: null,
  },
  {
    title: "Poke Bowl de Salmão",
    description: "O bowl havaiano que conquistou o mundo.",
    calories: 480, protein: 34, carbs: 48, fat: 16,
    prepTime: 15, cookTime: 15, servings: 2,
    category: "principal",
    tags: JSON.stringify(["sem-gluten", "sem-lactose", "alta-proteina"]),
    ingredients: JSON.stringify(["200g salmão fresco", "150g arroz sushi", "1 abacate", "edamame", "cenoura ralada", "pepino", "molho soja", "gergelim"]),
    steps: JSON.stringify(["Cozinhar arroz.", "Cortar salmão em cubos e marinar em soja.", "Montar bowl com arroz.", "Adicionar salmão, abacate, edamame e legumes.", "Polvilhar gergelim."]),
    imageUrl: null,
  },
  {
    title: "Lasanha de Legumes",
    description: "Reconfortante lasanha vegetariana sem carne.",
    calories: 380, protein: 16, carbs: 46, fat: 14,
    prepTime: 20, cookTime: 40, servings: 4,
    category: "principal",
    tags: JSON.stringify(["vegetariano"]),
    ingredients: JSON.stringify(["placas de lasanha", "1 curgete", "1 beringela", "400g tomate triturado", "bechamel light", "100g mozzarella", "azeite", "sal q.b."]),
    steps: JSON.stringify(["Grelhar legumes.", "Preparar molho de tomate.", "Montar camadas: massa, legumes, tomate, bechamel.", "Acabar com mozzarella.", "Assar 180ºC 35-40 min."]),
    imageUrl: null,
  },
  {
    title: "Tartare de Atum",
    description: "Elegante, fresco e rico em ómega-3.",
    calories: 240, protein: 30, carbs: 6, fat: 10,
    prepTime: 15, cookTime: 0, servings: 2,
    category: "principal",
    tags: JSON.stringify(["sem-gluten", "sem-lactose", "alta-proteina", "sem-acucar"]),
    ingredients: JSON.stringify(["250g atum fresco", "1 aguacate", "1 limão", "molho soja", "cebolinho", "gergelim", "gengibre ralado"]),
    steps: JSON.stringify(["Cortar atum em cubos pequenos.", "Misturar com soja, limão e gengibre.", "Cortar abacate em cubos.", "Montar tartare.", "Decorar com gergelim e cebolinho."]),
    imageUrl: null,
  },
  {
    title: "Galinhada Simples",
    description: "Arroz com frango à portuguesa. Comfort food saudável.",
    calories: 440, protein: 36, carbs: 48, fat: 10,
    prepTime: 10, cookTime: 35, servings: 3,
    category: "principal",
    tags: JSON.stringify(["sem-gluten", "sem-lactose", "alta-proteina"]),
    ingredients: JSON.stringify(["400g frango", "200g arroz", "1 cebola", "2 dentes alho", "1 tomate", "caldo", "açafrão", "sal e pimenta q.b.", "azeite"]),
    steps: JSON.stringify(["Refogar cebola, alho e frango.", "Adicionar tomate e açafrão.", "Juntar arroz e caldo.", "Cozinhar tapado 18-20 min."]),
    imageUrl: null,
  },
  {
    title: "Salada de Beterraba com Nozes",
    description: "Colorida, antioxidante e com contraste de texturas.",
    calories: 220, protein: 6, carbs: 24, fat: 12,
    prepTime: 10, cookTime: 0, servings: 2,
    category: "salada",
    tags: JSON.stringify(["sem-gluten", "vegetariano"]),
    ingredients: JSON.stringify(["2 beterrabas cozidas", "50g rúcula", "40g queijo de cabra", "30g nozes", "vinagre balsâmico", "mel", "azeite"]),
    steps: JSON.stringify(["Fatiar beterraba.", "Montar sobre rúcula.", "Adicionar queijo e nozes.", "Vinagrete de balsâmico, mel e azeite."]),
    imageUrl: null,
  },
  {
    title: "Polvo Grelhado com Batata",
    description: "Clássico português elevado a refeição fitness.",
    calories: 400, protein: 32, carbs: 38, fat: 12,
    prepTime: 10, cookTime: 50, servings: 2,
    category: "principal",
    tags: JSON.stringify(["sem-gluten", "sem-lactose", "alta-proteina"]),
    ingredients: JSON.stringify(["500g polvo cozido", "3 batatas", "4 dentes alho", "coentros", "azeite", "limão", "pimentão doce", "sal q.b."]),
    steps: JSON.stringify(["Cozer batatas.", "Grelhar polvo em grelha quente.", "Preparar molho de alho, coentros e azeite.", "Servir polvo com batata e molho."]),
    imageUrl: null,
  },
  {
    title: "Tarte de Vegetais Sem Massa",
    description: "Quiche sem massa: mais leve e sem glúten.",
    calories: 240, protein: 18, carbs: 10, fat: 15,
    prepTime: 10, cookTime: 30, servings: 4,
    category: "principal",
    tags: JSON.stringify(["sem-gluten", "vegetariano", "alta-proteina"]),
    ingredients: JSON.stringify(["4 ovos", "100ml natas light", "1 curgete", "1 pimento", "50g queijo ralado", "sal e pimenta q.b.", "ervas provençais"]),
    steps: JSON.stringify(["Bater ovos com natas.", "Misturar legumes cortados.", "Adicionar queijo e ervas.", "Verter em forma.", "Assar 180ºC 30 min."]),
    imageUrl: null,
  },
  {
    title: "Shakshuka",
    description: "Ovos escalfados em molho de tomate picante. Fusão incrível.",
    calories: 280, protein: 16, carbs: 20, fat: 16,
    prepTime: 5, cookTime: 20, servings: 2,
    category: "principal",
    tags: JSON.stringify(["sem-gluten", "sem-lactose", "vegetariano"]),
    ingredients: JSON.stringify(["4 ovos", "400g tomate triturado", "1 pimento", "1 cebola", "2 dentes alho", "paprika", "cominhos", "malagueta", "azeite", "coentros"]),
    steps: JSON.stringify(["Refogar cebola, pimento e alho.", "Adicionar especiarias.", "Juntar tomate e cozinhar 10 min.", "Criar espaços e partir ovos.", "Tapar e cozinhar 5-7 min."]),
    imageUrl: null,
  },
  {
    title: "Smoothie Verde com Proteína",
    description: "O smoothie pré-treino definitivo. Verde e poderoso.",
    calories: 310, protein: 25, carbs: 32, fat: 8,
    prepTime: 5, cookTime: 0, servings: 1,
    category: "bebida",
    tags: JSON.stringify(["sem-gluten", "alta-proteina"]),
    ingredients: JSON.stringify(["1 scoop proteína", "100g espinafres", "1 banana", "1 colher sopa manteiga amendoim", "200ml leite", "gelo"]),
    steps: JSON.stringify(["Colocar tudo no liquidificador.", "Triturar até homogéneo.", "Servir imediatamente."]),
    imageUrl: null,
  },
  {
    title: "Abacate Recheado com Ovo",
    description: "Pequeno-almoço low-carb rico em gorduras saudáveis.",
    calories: 290, protein: 12, carbs: 6, fat: 24,
    prepTime: 3, cookTime: 15, servings: 1,
    category: "pequeno-almoco",
    tags: JSON.stringify(["sem-gluten", "sem-lactose", "vegetariano"]),
    ingredients: JSON.stringify(["1 abacate", "2 ovos", "sal e pimenta q.b.", "paprika", "cebolinho"]),
    steps: JSON.stringify(["Cortar abacate ao meio e remover caroço.", "Ampliar cavidade.", "Partir ovo em cada metade.", "Temperar.", "Assar 180ºC 15 min."]),
    imageUrl: null,
  },
  {
    title: "Açorda de Bacalhau",
    description: "Tradição portuguesa numa versão mais leve.",
    calories: 360, protein: 30, carbs: 32, fat: 12,
    prepTime: 10, cookTime: 15, servings: 2,
    category: "principal",
    tags: JSON.stringify(["sem-lactose"]),
    ingredients: JSON.stringify(["200g bacalhau demolhado", "2 ovos", "2 fatias pão integral", "4 dentes alho", "coentros", "azeite", "sal q.b."]),
    steps: JSON.stringify(["Cozer bacalhau e desfiar.", "Fritar alho em azeite.", "Adicionar pão esfarelado.", "Juntar bacalhau e mexer.", "Adicionar ovos mexidos e coentros."]),
    imageUrl: null,
  },
  {
    title: "Tagliatelle de Curgete com Camarão",
    description: "Elegante, low-carb e cheio de sabor marítimo.",
    calories: 300, protein: 28, carbs: 12, fat: 14,
    prepTime: 10, cookTime: 10, servings: 2,
    category: "principal",
    tags: JSON.stringify(["sem-gluten", "sem-lactose", "alta-proteina"]),
    ingredients: JSON.stringify(["2 curgetes", "250g camarão", "3 dentes alho", "malagueta", "azeite", "vinho branco", "limão", "salsa"]),
    steps: JSON.stringify(["Espiralizar curgetes.", "Saltear alho em azeite.", "Adicionar camarão e vinho.", "Cozinhar 3-4 min.", "Misturar curgete e servir com salsa."]),
    imageUrl: null,
  },
  {
    title: "Bolo de Aveia e Banana Sem Açúcar",
    description: "Bolo fofinho e natural. Lanche saudável sem culpa.",
    calories: 160, protein: 5, carbs: 26, fat: 5,
    prepTime: 10, cookTime: 35, servings: 8,
    category: "sobremesa",
    tags: JSON.stringify(["sem-gluten", "vegetariano", "sem-acucar"]),
    ingredients: JSON.stringify(["3 bananas maduras", "200g aveia", "2 ovos", "1 colher chá canela", "1 colher chá fermento", "extracto baunilha"]),
    steps: JSON.stringify(["Esmagar bananas.", "Misturar com ovos e aveia.", "Adicionar canela, baunilha e fermento.", "Verter em forma.", "Assar 175ºC 35 min."]),
    imageUrl: null,
  },
];

async function seed() {
  console.log(`Inserindo ${data.length} receitas adicionais...`);
  for (let i = 0; i < data.length; i += 10) {
    const batch = data.slice(i, i + 10);
    await db.insert(recipes).values(batch);
    console.log(`✅ ${Math.min(i + 10, data.length)}/${data.length}`);
  }
  console.log("🎉 Concluído!");
  process.exit(0);
}

seed().catch((e) => { console.error(e); process.exit(1); });
